name: CI

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.15", "1.16"]
        eureka: ["1.1.147", "1.3.1"]
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Launch Eureka
        env:
          EUREKA_VERSION: ${{ matrix.eureka }}
        run: |
          cp docker-compose.override.yml.dist docker-compose.override.yml
          docker-compose up -d
          echo "Waiting for Eureka to come up"
          sleep 120

      - name: Run tests
        run: go test -v ./...
